var _ = require('underscore')
	, defaultGC = {
		siteId: 1000009125,
		username: 'Oodle-Email',
		password: 'Ood!e-Em@il',
		firstName: 'Charles',
		lastName: 'Shaw',
		emailAddress: '2486327771c2567@anon.oodle.com',
		phone: 1234567890,
		extension: 12345,
		comments: 'qa Is this an unfurnished rental - (autogenerated by guest card test form) ',
		moveDate: '2014-02-27',
		bedrooms: 1,
		bathrooms: 1,
		sendEmailConfirmation: 1,
		byEmail: 1,
		userSocialHtml: '',
		listingTitle: '1 Bed - Christina Lakes Alaska - Polar Dr. for $1400 - $1450',
		listingUrl: 'http//apps.facebook.com/marketplace/view/2486327771',
		userImageUrl: 'http//i.oodleimg.com/user/46733438_1297209078.jpg',
		replyTo: '',
		userSocialUrl: 'http//webservice.rrobinson.frlabs.com/tools/sampleOodleHtml.php',
		featListingSiteId: 1000009125,
		responseType: 'xml',
		version: 1,
		guestCardDate: '2014-01-01 22:22:22'
	};

module.exports = function(gc) {
	gc = gc || {};
	var updated = _.defaults(gc.update || {}, defaultGC);
	updated.comments = updated.comments+(new Date().getTime());
	return _.omit(updated, gc.omit || {});
}